spring:
  application:
    name: ShieldMe-Authentication-Service

# --- Database Configurations ---
  data:
    mongodb:
      uri: mongodb://localhost:27017/ShieldMe  # MongoDB URI
      database: ShieldMe
      auto-index-creation: true



# --- Server Error Configurations ---
server:
  error:
    include-binding-errors: always
    include-message: always
    include-stacktrace: never
    include-exception: true
  port: 8080  # Server port configuration   tdhfuvcxlsywaolh


  mail:
    host: smtp.gmail.com
    port: 587
    username: "yraj30284@gmail.com"
    password: "tdhfuvcxlsywaolh"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
