spring:
  application:
    name: SOS-Alerts-Service
  data:
    mongodb:
#      uri: mongodb://localhost:27017/ShieldMe

      uri: mongodb+srv://ajaynegi3345:m7CdBtFBJz4xFVcT@mongocluster.epkox.mongodb.net/?retryWrites=true&w=majority&appName=MongoCluster
      database: ShieldMe
      auto-index-creation: true


  mail:
    host: smtp.gmail.com
    port: 587

    #username: # --- Add Email from which all emails are going to send ---
    #password: # --- Generate application password for that email id from google console ---
    username: codiescoder@gmail.com
    password: nhxvxwgsthvypwjq

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 8081